# Generated by Django 5.2.17 on 2026-08-05 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0003_alter_favorite_quote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='quote_id',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='quote_id muss buch-abschnitt (5-23), e-kapitel (e-53) oder s-kapitel[-paragraph] (s-4-2) sein', regex='^(\\d{1,2}-\\d{1,3}|e-\\d{1,2}|s-\\d{1,2}(-\\d{1,2})?)$')]),
        ),
    ]
